### PR TITLE
Format sources with Black, added annotations and sort imports

### PR DESCRIPTION
**Pull request by FeodorFitsner**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
As with all bool/int/float properties I'd like to add type validations for enum-like setters. For example, I tried enforcing a strict list of values for `Textbox.align` using `Literal` constraint and it worked: https://github.com/pglet/pglet-python/pull/61/commits/3b8562ba789987ff7c2990f8a0afa697d4ab292c

image

@mikaelho is it a recommended way to do that? Should we use `Enum`s instead?

**Comment by mikaelho** [comment]
I think that the error message is quite nice and clear, and I do not think we will get anything better with enums.

Situation might be different if you already had the enums defined for some other purpose, but since this does not seem to be the case, they would add little value. Especially since the beartype enum story looks quite complicated/confusing when compared to e.g. pydantic.

**Comment by FeodorFitsner** [comment]
Thanks for your thoughts! Yep, I've tried the same with Enums and didn't like the result. Also, code-completion in VS Code works nicers with just string literals. OK, I'm forward with string literals then.

**Comment by FeodorFitsner** [comment]
@MrHemlock as you are currently working on adding typings/docs (thank you!) you might need to refresh your fork as I've just merged this PR with *some* type checks and black formatting.

**Pull request merged**
