### PR TITLE
Fix tabs initial value and setting Tab.control to None

### PR DESCRIPTION
**Pull request by mikaelho**
Minor fixes for issues noted when adding the "change tab with buttons" sample:

- `Tabs` does not initially have `value` set
- Setting `Tab.controls` to `None` causes an unnecessary exception

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Sorry for 🐢. VS Code is good at messing with imports on mistypes.

**Comment by FeodorFitsner** [comment]
I'm not sure I understand the point of having both `self.__tabs` and `self.tabs` where `self.__tabs` is not initially set: https://github.com/pglet/pglet-python/blob/44861b4f98628663aa6cc8ad74982c5c86de715b/pglet/tabs.py#L36-L37 Am I missing some pattern - could you please elaborate?

**Comment by mikaelho** [comment]
Good discussion topic! Main idea was that the code for managing a property is centralized in the property, making it the properties responsibility to handle all acceptable values and to make sure things are left in a coherent state.

Centralising logic to properties this way seems especially good when there is a relationship between two properties like `tabs` and `value`.

Just updated a little bit, enforcing also that `value` can only be set to a sensible value (not to `None`, and to an empty string only if there are no tabs)

Here we let the property manage the case where `tabs` is `None` (valid value since I have assumed that we want to let the developer set `t.tabs = None`). On the other hand, we check that `value` is not `None` in `__init__`, because it is not a valid value (in `__init__`, `None` is just an alias for "not here").

Don't know if all that makes sense to you.

**Comment by mikaelho** [comment]
> Sorry for 🐢. VS Code is good at messing with imports on mistypes.

😁

Does VS Code have an option of cleaning up imports any time the file is saved?

**Comment by FeodorFitsner** [comment]
Ah, sorry, I've got confused by `self.tabs = tabs` in the constructor, but, apparently, it's a property called, not a field set! It all makes sense now :) Merging.

**Comment by FeodorFitsner** [comment]
Re: sorting on save - will take a look. It's a bit trickier than configuring Black.

**Comment by FeodorFitsner** [comment]
So, I've added a section about formatting and sorting with VS Code here: https://github.com/pglet/pglet-python/blob/main/CONTRIBUTING.md#code-formatting - feel free to add guidelines for other IDEs.

**Pull request merged**
